//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonDataTransforms.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmazonDataTransforms.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:   0
        ///ASIN: 0771044445
        ///  discontinued product
        ///.
        /// </summary>
        internal static string Discontinued {
            get {
                return ResourceManager.GetString("Discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:   5
        ///ASIN: 1577943082
        ///  title: Prayers That Avail Much for Business: Executive
        ///  group: Book
        ///  salesrank: 455160
        ///  similar: 5  157794349X  0892749504  1577941829  0892749563  1577946006
        ///  categories: 2
        ///   |Books[283155]|Subjects[1000]|Religion &amp; Spirituality[22]|Christianity[12290]|Worship &amp; Devotion[12465]|Prayerbooks[12470]
        ///   |Books[283155]|Subjects[1000]|Religion &amp; Spirituality[22]|Christianity[12290]|Christian Living[12333]|Business[297488]
        ///  reviews: total: 0  downloaded: 0  avg rating: 0        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoReviews {
            get {
                return ResourceManager.GetString("NoReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Full information about Amazon Share the Love products
        ///Total items: 548552
        ///
        ///Id:   0
        ///ASIN: 0771044445
        ///  discontinued product
        ///
        ///Id:   1
        ///ASIN: 0827229534
        ///  title: Patterns of Preaching: A Sermon Sampler
        ///  group: Book
        ///  salesrank: 396585
        ///  similar: 5  0804215715  156101074X  0687023955  0687074231  082721619X
        ///  categories: 2
        ///   |Books[283155]|Subjects[1000]|Religion &amp; Spirituality[22]|Christianity[12290]|Clergy[12360]|Preaching[12368]
        ///   |Books[283155]|Subjects[1000]|Religion &amp; Spirituality[22]|C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductsAndHeader {
            get {
                return ResourceManager.GetString("ProductsAndHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:   1
        ///ASIN: 0827229534
        ///  title: Patterns of Preaching: A Sermon Sampler
        ///  group: Book
        ///  salesrank: 396585
        ///  similar: 5  0804215715  156101074X  0687023955  0687074231  082721619X
        ///  categories: 2
        ///   |Books[283155]|Subjects[1000]|Religion &amp; Spirituality[22]|Christianity[12290]|Clergy[12360]|Preaching[12368]
        ///   |Books[283155]|Subjects[1000]|Religion &amp; Spirituality[22]|Christianity[12290]|Clergy[12360]|Sermons[12370]
        ///  reviews: total: 2  downloaded: 2  avg rating: 5
        ///    2000-7-28  cutomer: A2JW67OY8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleProduct {
            get {
                return ResourceManager.GetString("SimpleProduct", resourceCulture);
            }
        }
    }
}
